### ISSUE TITLE
Declaration of BrianFaust\Reviewable\ReviewableServiceProvider::boot(): BrianFaust\Reviewable\void must be compatible with BrianFaust\ServiceProvider\AbstractServiceProvider::boot(): BrianFaust\ServiceProvider\void

### ISSUE THREAD

**Issue by AlexBuitrago** [faustbrian/Laravel-Reviewable#15]
- Version of package: 2.1
- PHP Version: 7.1.2
- Framework Laravel: 5.4

I have it issue:
```Declaration of BrianFaust\Reviewable\ReviewableServiceProvider::boot(): BrianFaust\Reviewable\void must be compatible with BrianFaust\ServiceProvider\AbstractServiceProvider::boot(): BrianFaust\ServiceProvider\void```

Do you know how to solve it?

**Comment by N02SRT** [comment]
Now I am also getting this error. Is there a solution?

Thanks!

**Comment by faustbrian** [comment]
Something is wrong with your PHP Version as it doesn't recognize the `void` return type.
