### ISSUE TITLE
PresentableTrait not found

### ISSUE THREAD

**Issue by azcoppen** [faustbrian/Laravel-Reviewable#2]
When calling $user->reviews()

FatalErrorException in Review.php line 25:
Trait 'DraperStudio\Database\Traits\Models\PresentableTrait' not found

File not available in Laravel-Reviewable package?

When adding Laravel-Database package to resolve the dependencies

composer require draperstudio/laravel-database:1.0.*@dev
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - draperstudio/laravel-database v1.0.2 requires draperstudio/laravel-service-provider ^1.0 -> satisfiable by draperstudio/laravel-service-provider[1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - draperstudio/laravel-database v1.0.1 requires draperstudio/laravel-service-provider ^1.0 -> satisfiable by draperstudio/laravel-service-provider[1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - draperstudio/laravel-database v1.0.0 requires draperstudio/laravel-service-provider ~1.0 -> satisfiable by draperstudio/laravel-service-provider[1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for draperstudio/laravel-database 1.0.*@dev -> satisfiable by draperstudio/laravel-database[v1.0.0, v1.0.1, v1.0.2].

**Comment by DraperStudio** [comment]
Need to update the dependencies at some time to https://github.com/DraperStudio/Eloquent-Presenter
